version: '3'

services:
  torchserve:
    image: pytorch/torchserve:0.8.1-gpu
    container_name: torchserve_container
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "7070:7070"
      - "7071:7071"
        #runtime: nvidia
    volumes:
      - $PWD/torchserve_artifacts/config.properties:/home/model-server/config.properties
      - $PWD/torchserve_artifacts/model-server:/tmp/models
    command: torchserve --model-store=/tmp/models
    shm_size: '1g'
    ulimits:
      memlock: -1
      stack: 67108864

  nextjs_frontend:
    container_name: nextjs_container
    build:
      context: ui_frontend/ 
      dockerfile: ui_frontend/Dockerfile
    ports:
      - "3000:3000"
      
  fastapi_service:
    container_name: fastapi_container
    ports:
      - "9080:9080"
    volumes:
      - $PWD/server_backend/requirements.txt:/app/requirements.txt
      - ~/.aws:/root/.aws  # Mounting AWS credentials
    build:
      context: server_backend/
      dockerfile: server_backend/Dockerfile
    environment: 
      - PORT=9080
